### ISSUE TITLE
Nice job

### ISSUE THREAD

**Issue by Th3SnowyOwl** [AnonymousHacker1279/EarthScienceProject#1]
Have a good day hope you see this lol

**Comment by AnonymousHacker1279** [comment]
Thanks, but uhh, why would you create an issue for this? It's designed for bug reports and feature requests.

**Comment by Th3SnowyOwl** [comment]
ik lol why are up rn lmao

**Comment by Th3SnowyOwl** [comment]
I was going to close it.

**Comment by AnonymousHacker1279** [comment]
> ik lol why are up rn lmao

Sleep schedule doesn't exist, also use Discussions instead of issue requests so it doesn't clog my feed and send out emails.
